### ISSUE TITLE
About the installation 

### ISSUE THREAD

**Issue by irhallac** [HuangJunJie2017/BEVDet#112]
In the installation steps https://github.com/HuangJunJie2017/BEVDet/blob/dev2.0/docs/en/getting_started.md
`git clone https://github.com/open-mmlab/mmdetection3d.git`
is this needed or should it be the bevdet repo: `https://github.com/HuangJunJie2017/BEVDet.git` ?

**Comment by HuangJunJie2017** [comment]
@irhallac  use https://github.com/HuangJunJie2017/BEVDet.git instead of https://github.com/open-mmlab/mmdetection3d.git

**Comment by foolhard** [comment]
Hello, 

Thanks for your great job and sharing the code. 

I have several questions about mmdet3d version and 
1. Does this mean that dev.2.0 repo is changed to mmdet3d 1.0+ version and use the new coordinate system in mmdet3d latest version? 
`use the origin of ego coordinate system as the center of the receptive field instead of the Lidar's.`

2. Do I need to process nuScenes dataset again, if I have the dataset processed by mmdet3d v0.11.0 ?

**Comment by HuangJunJie2017** [comment]
@foolhard 
1. yes
2. yes, you need to reprocess the nuScenes dataset
