### ISSUE TITLE
Question about accelerate=True in view_transformer

### ISSUE THREAD

**Issue by s-ryosky** [HuangJunJie2017/BEVDet#126]
When evaluating your trained BEVDet-R50-4D-Depth-CBGS model (bevdet4d-r50-depth-cbgs.pth) with the "accelerate" argument in view_transformer set to True, the recognition accuracy including mAP and NDS decreases.
Is that reasonable result?

When accelerate=True, the evaluation results are as follows:
mAP: 0.2259
mATE: 0.7957
mASE: 0.2941
mAOE: 0.7604
mAVE: 2.0035
mAAE: 0.3604
NDS: 0.2919

Additionally, when accelerate=True and align_after_view_transformation=True, the evaluation results are as follows:
mAP: 0.3862
mATE: 0.6230
mASE: 0.2754
mAOE: 0.4631
mAVE: 0.2822
mAAE: 0.1900
NDS: 0.5097

**Comment by HuangJunJie2017** [comment]
@s-ryosky 
1. accelerate=True and align_after_view_transformation=False is not reasonable, i will add assertion to forbid this configuration. 
2. accelerate=True and align_after_view_transformation=True is reasonable. The precision degeneration is derive from the fix extrinsic parameters caused by using 'accelerate=True'. In fact, different video clips have serveral different extrinsic parameters.

**Comment by s-ryosky** [comment]
Thank you for your reply.
