### ISSUE TITLE
bevpoolv2‘s performance vs bevpool

### ISSUE THREAD

**Issue by AndyYuan96** [HuangJunJie2017/BEVDet#150]
Hi，I train a model with bevpool，and use bevpoolv2 to inference，I find the result is almost the same，but still has little difference。In nuscenes val，bevpoolv2 with mAP 0.6570 and NDS 0.6828，bevpool with mAP 0.6574 and NDS 0.6834，I just wonder does it is normal？does bevpoolv2 and bevpool generate exactly the same output。

**Comment by HuangJunJie2017** [comment]
@AndyYuan96  does bevpoolv2 and bevpool generate exactly the same output？ 
Yes in theory.
In practice, doesn't, as bevpoolv2 need not compute and store the frustum feature as an intermediary result.
The output of bevpoolv2 is close to bevpool but not exactly equal to it on account of the precision degeneration (f32?) caused by storing the frustum feature.

**Comment by AndyYuan96** [comment]
> @AndyYuan96 does bevpoolv2 and bevpool generate exactly the same output？
> Yes in theory.
> In practice, doesn't, as bevpoolv2 need not compute and store the frustum feature as an intermediary result.
> The output of bevpoolv2 is close to bevpool but not exactly equal to it on account of the precision degeneration (f32?) caused by storing the frustum feature.

got it，thanks。
