### ISSUE TITLE
Questions about retraining

### ISSUE THREAD

**Issue by gaojunbin** [HuangJunJie2017/BEVDet#20]
Hi. When I retrain BEVDet-sttiny with the config file bevdet-sttiny.py for 20 epochs, I get the result on val set:
```
mAP: 0.3049

mATE: 0.6762
mASE: 0.2743
mAOE: 0.5235
mAVE: 0.9782
mAAE: 0.2653
NDS: 0.3807
Eval time: 103.4s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.509   0.539   0.160   0.118   0.946   0.227
truck   0.209   0.677   0.219   0.113   0.955   0.222
bus     0.326   0.677   0.187   0.087   2.124   0.468
trailer 0.157   1.020   0.231   0.375   1.061   0.173
construction_vehicle    0.069   0.829   0.484   1.126   0.096   0.375
pedestrian      0.333   0.750   0.305   1.360   0.882   0.544
motorcycle      0.243   0.729   0.265   0.618   1.544   0.110
bicycle 0.198   0.543   0.281   0.794   0.217   0.002
traffic_cone    0.501   0.512   0.324   nan     nan     nan
barrier 0.503   0.486   0.286   0.120   nan     nan
```
It seems the NDS is lower than the model you provided (38.1 v.s 40.4). 
More information can be seen in the log file (http://www.junbin.xyz/fileURL/20220607_222110.log). Can you help me? Thanks.

**Comment by HuangJunJie2017** [comment]
@gaojunbin 
It seems that the poorer velocity prediction accounts for the main performance degeneration. As both mAVE and mAAE are relevant to the velocity prediction. 
I conjecture that it is because it is not stable for vision-based velocity predicting with single frame data. 
I have trained this configuration for several times and have observed a variance of training results. 40.4 NDS is the latest one. And the results in the paper is 39.4 NDS for BEVDet-tiny, which is conducted six months ago with exactly the same configuration.  
BEVDet4D is more stable in this aspect, which is recommended. 
By the way, have you test the epoch 18 or 19?

**Comment by gaojunbin** [comment]
@HuangJunJie2017 
Thanks to your reply.
The results of epoch 18&19 are shown below. It seems no much difference with epoch 20. 
So is it normal for the training results of BEVDet-tiny to have some instability? 
```
# epoch 19
mAP: 0.3052
mATE: 0.6768
mASE: 0.2749
mAOE: 0.5221
mAVE: 0.9736
mAAE: 0.2658
NDS: 0.3813

# epoch 18
mAP: 0.3072
mATE: 0.6778
mASE: 0.2752
mAOE: 0.5351
mAVE: 0.9879
mAAE: 0.2651
NDS: 0.3795
Eval time: 106.5s
```

**Comment by HuangJunJie2017** [comment]
@gaojunbin Small instability is normal but i haven't seems bevdet-tiny below 39 NDS in my training. So far, I am not sure whether there is some other problem.  I would like to collect more retraining samples, before making the final judgement.

**Comment by gaojunbin** [comment]
@HuangJunJie2017 
I see. Thanks for your help. I will also find time to retrain to check if the results are normal.
