### ISSUE TITLE
question about the positional shift between two candidate feature

### ISSUE THREAD

**Issue by midpushgogo** [HuangJunJie2017/BEVDet#35]
It says in the paper that the network predict position shifting that is irrelevant to the ego-motion, but it seems like the position shifting is given as input. As i know, the  aligned matrix is given in the dataset pipeline.
May i ask which part is the network predict the position shift

**Comment by HuangJunJie2017** [comment]
@midpushgogo  The velocity target generated by mmdet3d data preparation has been irrelevant to the ego_motion. So we do not have to adjust the target as we build bevdet4d upon mmdet3d. However, we need the aligned matrix to align the BEV feature. So that the offset shifting of content in the features of the two adjacent frames is irrelevant to the ego_motion and is consistent with the target.

**Comment by midpushgogo** [comment]
so the aligned matrix is given as input and the network doesnt predict it , am i right ?

**Comment by HuangJunJie2017** [comment]
@midpushgogo yes

**Comment by midpushgogo** [comment]
thank you !
